[tool.poetry]
name = "pepperpy-core"
version = "2.0.1"
description = "Core package for PepperPy Framework"
authors = ["Felipe Pimentel <fpimentel88@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
python_dotenv = "^1.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
