[tool.poetry]
name = "pepperpy-core"
version = "0.1.0"
description = "Core functionality for PepperPy framework"
authors = ["Felipe Pimentel <fpimentel88@gmail.com>"]
readme = "README.md"
packages = [
    { include = "pepperpy_core" },
    { include = "examples" },
]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
pydantic = "^2.0.0"
typing-extensions = "^4.0.0"
redis = { version = "^4.0.0", optional = true }

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.0.1"

[tool.poetry.extras]
redis = ["redis"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --cov=pepperpy_core --cov-report=term-missing"
filterwarnings = [
    "ignore:Support for class-based.*:DeprecationWarning:pydantic",
]

[tool.mypy]
python_version = "3.9"
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
check_untyped_defs = true
implicit_reexport = true
