metrics:
  exporters:
    prometheus:
      port: 8000
      path: /metrics
    
    opentelemetry:
      endpoint: http://localhost:4317
      protocol: grpc

logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    - type: console
    - type: file
      filename: logs/pepperpy.log
      maxBytes: 10485760  # 10MB
      backupCount: 5

tracing:
  service_name: pepperpy
  sample_rate: 1.0
  exporters:
    jaeger:
      agent_host: localhost
      agent_port: 6831 