repos:
  - repo: local
    hooks:
      - id: black
        name: Black
        entry: poetry run black
        language: system
        types: [python]
        args: ["--check"]

      - id: ruff
        name: Ruff
        entry: poetry run ruff
        language: system
        types: [python]
        args: ["--fix", "--exit-zero"]
