[tool.poetry]
name = "pepperpy"
description = "A modern Python utility library"
authors = ["Felipe Pimentel <fpimentel88@gmail.com>"]
readme = "README.md"
version = "1.2.5"
repository = "https://github.com/felipepimentel/pepperpy"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.9.2"
typer = "^0.12.5"
rich = "^13.9.3"
tokenizers = "^0.20.1"
questionary = "^2.0.0"
plotext = "^5.2.8"

sqlalchemy = { version = "^2.0.27", optional = true }
alembic = { version = "^1.13.1", optional = true }
greenlet = { version = "^3.0.3", optional = true }

asyncpg = { version = "^0.29.0", optional = true }
psycopg = { version = "^3.1.18", optional = true }
pymysql = { version = "^1.1.0", optional = true }
aiosqlite = { version = "^0.19.0", optional = true }
aiomysql = { version = "^0.2.0", optional = true }
duckdb = { version = "^0.10.0", optional = true }

redis = { version = "^5.0.1", optional = true }
msgpack = { version = "^1.0.7", optional = true }

prometheus-client = { version = "^0.19.0", optional = true }
opentelemetry-api = { version = "^1.23.0", optional = true }
opentelemetry-sdk = { version = "^1.23.0", optional = true }
opentelemetry-instrumentation-sqlalchemy = { version = "^0.44b0", optional = true }

[tool.poetry.extras]
postgresql = ["sqlalchemy", "asyncpg", "psycopg", "alembic", "greenlet"]
mysql = ["sqlalchemy", "pymysql", "aiomysql", "alembic", "greenlet"]
sqlite = ["sqlalchemy", "aiosqlite", "alembic", "greenlet"]
duckdb = ["duckdb"]

redis_cache = ["redis", "msgpack"]

monitoring = ["prometheus-client", "opentelemetry-api", "opentelemetry-sdk", "opentelemetry-instrumentation-sqlalchemy"]

ai = ["torch", "sentence-transformers", "scikit-learn", "wandb", "faiss-cpu", "qdrant-client"]
ui = ["textual", "questionary", "plotext"]

all = [
  "sqlalchemy", "alembic", "greenlet",
  "asyncpg", "psycopg", "pymysql", "aiomysql", "aiosqlite", "duckdb",
  "redis", "msgpack",
  "prometheus-client", "opentelemetry-api", "opentelemetry-sdk", "opentelemetry-instrumentation-sqlalchemy",
  "torch", "sentence-transformers", "scikit-learn", "wandb", "faiss-cpu", "qdrant-client",
  "textual", "questionary", "plotext"
]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
pytest-asyncio = "^0.23.5"
pytest-cov = "^4.1.0"
black = "^24.10.0"
ruff = "^0.7.1"
mypy = "^1.13.0"
python-semantic-release = "^9.12.0"
types-redis = "^4.6.0.20240311"
sqlalchemy-stubs = "^0.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
select = [
    "E", "F", "B", "I", "N",
    "RUF",
    "UP",
    "ANN",
]
ignore = [
    "E501",
    "N812",
    "B006",
    "ANN101",
    "ANN102",
]
line-length = 100

[tool.ruff.per-file-ignores]
"pepperpy/ai/optimization/*.py" = ["N803"]
"tests/*" = ["ANN"]

[tool.black]
line-length = 100
target-version = ['py310']
include = '\.pyi?$'

[tool.mypy]
python_version = "3.12"
strict = true
plugins = ["sqlalchemy.ext.mypy.plugin"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "--cov=pepperpy --cov-report=term-missing"

[tool.semantic_release]
version_variable = [
    "pepperpy/__init__.py:__version__",
    "pyproject.toml:tool.poetry.version"
]
branch = "main"
upload_to_pypi = true
build_command = "poetry build"