[tool.poetry]
name = "pepperpy"
description = "A simple Python project template"
authors = ["Felipe Pimentel <fpimentel88@gmail.com>"]
readme = "README.md"
version = "0.0.0"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.extras]
console = ["rich"]
logging = ["loguru"]
api = ["requests"]
database = ["sqlite3", "redis"]
file = ["csv", "json"]

[tool.poetry.group.dev.dependencies]
semantic-release = "^0.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = [
    "pyproject.toml:tool.poetry.version"
]
branch = "main"
changelog_file = "CHANGELOG.md"
build_command = "pip install poetry && poetry build"
