[tool.poetry]
name = "pepperpy-codebase"
version = "0.1.0"
description = "PepperPy pepperpy-codebase package"
authors = ["Felipe Pimentel <fpimentel88@gmail.com>"]
readme = "README.md"
packages = [
    { include = "pepperpy_codebase" },
]

[tool.poetry.dependencies]
python = "^3.12"
pepperpy-core = {path = "../pepperpy-core", develop = true}
pepperpy-db = {path = "../pepperpy-db", develop = true}
pepperpy-console = {path = "../pepperpy-console", develop = true}

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
pytest-asyncio = "^0.23.5"
pytest-cov = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.setuptools.package-data]
"pepperpy_codebase" = ["py.typed"]
