[tool.poetry]
name = "pepperpy-db"
version = "0.1.0"
description = "PepperPy pepperpy-db package"
authors = ["Felipe Pimentel <fpimentel88@gmail.com>"]
readme = "README.md"
packages = [
    { include = "pepperpy_db" },
]

[tool.poetry.dependencies]
python = "^3.12"
pepperpy-core = {path = "../pepperpy-core", develop = true}
sqlalchemy = "^2.0.0"
asyncpg = "^0.29.0"
duckdb = {version = "^0.9.0", optional = true}

[tool.poetry.extras]
duckdb = ["duckdb"]

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
pytest-asyncio = "^0.23.5"
pytest-cov = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.setuptools.package-data]
"pepperpy_db" = ["py.typed"]

[tool.mypy]
ignore_missing_imports = true
namespace_packages = true
explicit_package_bases = true
mypy_path = "../"
