[tool.poetry]
name = "pepperpy-ai"
version = "0.1.0"
description = "PepperPy AI package"
authors = ["Felipe Pimentel <fpimentel88@gmail.com>"]
readme = "README.md"
packages = [
    { include = "pepperpy_ai" },
]

[tool.poetry.dependencies]
python = "^3.12"
pepperpy-core = { path = "../pepperpy-core", develop = true }
openai = {version = "^1.0.0", optional = true}
anthropic = {version = "^0.7.0", optional = true}
aiohttp = {version = "^3.9.0", optional = true}
tenacity = {version = "^8.2.0", optional = true}
sentence-transformers = {version = "^2.0.0", optional = true}

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
pytest-asyncio = "^0.23.5"
pytest-cov = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.setuptools.package-data]
"pepperpy_ai" = ["py.typed"]

[tool.poetry.extras]
providers = [
    "openai",
    "anthropic",
    "aiohttp",
    "tenacity",
    "sentence-transformers"
]
