# Extend base ruff config
extend = "../../tools/lint/ruff.toml"

# Additional configurations specific to development tools
[lint]
ignore = [
    "S603",  # Ignore subprocess security warnings for dev tools - these are trusted paths
    "S607",  # Ignore partial executable path warnings for dev tools
]

# Exclude specific files if needed
exclude = [] 