"""Type stubs for nox sessions."""

from pathlib import Path
from typing import Any

class Session:
    """Nox session object."""

    def __init__(self) -> None: ...
    def install(self, *args: str, **kwargs: Any) -> None: ...
    def run(self, *args: str, **kwargs: Any) -> None: ...
    def log(self, message: str) -> None: ...
    def debug(self, message: str) -> None: ...
    def warn(self, message: str) -> None: ...
    def error(self, message: str) -> None: ...
    @property
    def bin(self) -> Path: ...
    @property
    def virtualenv(self) -> Path: ...
    @property
    def python(self) -> str: ...
