[tool.poetry]
name = "pepperpy-files"
version = "0.1.0"
description = "File handling module for PepperPy Framework"
authors = ["Felipe Pimentel <fpimentel88@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pepperpy-core = { path = "../pepperpy-core", develop = true }

[tool.poetry.extras]
epub = ["ebooklib", "beautifulsoup4"]
image = ["Pillow"]
yaml = ["pyyaml"]

[tool.poetry.group.dev.dependencies]
ebooklib = "^0.18.0"
beautifulsoup4 = "^4.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
