[tool.poetry]
name = "pepperpy-files"
version = "0.1.0"
description = "PepperPy files package"
authors = ["Felipe Pimentel <fpimentel88@gmail.com>"]
readme = "README.md"
packages = [
    { include = "pepperpy_files" },
]

[tool.poetry.dependencies]
python = "^3.12"
pepperpy-core = {path = "../pepperpy-core", develop = true}
numpy = "^1.24.0"
pydub = "^0.25.1"
pyyaml = "^6.0.1"
pandas = "^2.0.0"
Pillow = "^10.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
pytest-asyncio = "^0.23.5"
pytest-cov = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.setuptools.package-data]
"pepperpy_files" = ["py.typed"]
