[tool.poetry]
name = "pepperpy-console"
version = "0.1.0"
description = "Console utilities for PepperPy Framework"
authors = ["Felipe Pimentel <fpimentel88@gmail.com>"]
readme = "README.md"
packages = [
    { include = "pepperpy_console" },
]

[tool.poetry.dependencies]
python = "^3.12"
rich = "^13.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
pytest-asyncio = "^0.23.5"
pytest-cov = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
