name: Release and Publish Package

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install --no-root

      - name: Try to Build and Publish
        id: publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          set -e

          # Define a function to attempt publish
          attempt_publish() {
            poetry build
            poetry publish --username __token__ --password $PYPI_TOKEN
          }

          # Try initial publish
          if ! attempt_publish; then
            echo "Publishing failed, incrementing version and retrying..."
            
            # Bump version patch and retry
            poetry version patch
            NEW_VERSION=$(poetry version -s)
            echo "New version: $NEW_VERSION"
            git commit -am "Bump version to $NEW_VERSION"
            git tag -a "v${NEW_VERSION}" -m "Release v${NEW_VERSION}"
            git push origin main --tags

            # Retry publishing with the new version
            attempt_publish
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
