name: Release and Publish Package

on:
  push:
    branches:
      - main

jobs:
  release:
    if: github.repository == 'felipepimentel/pepperpy'

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install --no-root

      - name: Configure Git User
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"

      - name: Bump version and Tag
        id: versioning
        run: |
          # Verifica se a versão existe no PyPI
          VERSION_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" https://pypi.org/project/pepperpy/$(poetry version -s)/)
          if [ "$VERSION_EXISTS" -eq 200 ]; then
            echo "Version already exists on PyPI. Bumping version..."
            poetry version patch
          fi
      
          NEW_VERSION=$(poetry version -s)
          echo "New version: $NEW_VERSION"
          git commit -am "Bump version to $NEW_VERSION"
          git tag -a "v${NEW_VERSION}" -m "Release v${NEW_VERSION}"
          git push origin main --tags
        

      - name: Build the package
        run: poetry build

      - name: Publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry publish --username __token__ --password $PYPI_TOKEN

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ steps.versioning.outputs.version }}"
          release_name: "Release v${{ steps.versioning.outputs.version }}"
          body: "Automatic release of version v${{ steps.versioning.outputs.version }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./dist/*
          asset_name: "${{ steps.versioning.outputs.version }}-asset"
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
