name: Release and Publish Package

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install --no-root

      - name: Bump version and Tag
        id: versioning
        run: |
          # Bump version and get new version string
          poetry version patch
          NEW_VERSION=$(poetry version -s)
          echo "New version: $NEW_VERSION"
          git commit -am "Bump version to $NEW_VERSION"
          git tag -a "v${NEW_VERSION}" -m "Release v${NEW_VERSION}"
          git push origin main --tags

      - name: Build the package
        run: poetry build

      - name: Publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          if [ -z "${{ secrets.PYPI_TOKEN }}" ]; then
            echo "Error: PYPI_TOKEN is not set."
            exit 1
          fi
          poetry publish --username __token__ --password $PYPI_TOKEN

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1.1.0  # Atualizado para uma versão compatível com Node 20
        with:
          files: dist/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
